USE [master]
GO

/****** Object:  Database [REAL_ESTATE]    Script Date: 2/5/2020 11:20:47 AM ******/
CREATE DATABASE [REAL_ESTATE]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'REAL_ESTATE', FILENAME = N'I:\SQL2019\DATADIR\MSSQL15.MYSQLDB\MSSQL\DATA\REAL_ESTATE.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'REAL_ESTATE_log', FILENAME = N'I:\SQL2019\DATADIR\MSSQL15.MYSQLDB\MSSQL\DATA\REAL_ESTATE_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [REAL_ESTATE].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [REAL_ESTATE] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [REAL_ESTATE] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [REAL_ESTATE] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [REAL_ESTATE] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [REAL_ESTATE] SET ARITHABORT OFF 
GO

ALTER DATABASE [REAL_ESTATE] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [REAL_ESTATE] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [REAL_ESTATE] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [REAL_ESTATE] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [REAL_ESTATE] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [REAL_ESTATE] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [REAL_ESTATE] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [REAL_ESTATE] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [REAL_ESTATE] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [REAL_ESTATE] SET  DISABLE_BROKER 
GO

ALTER DATABASE [REAL_ESTATE] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [REAL_ESTATE] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [REAL_ESTATE] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [REAL_ESTATE] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [REAL_ESTATE] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [REAL_ESTATE] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [REAL_ESTATE] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [REAL_ESTATE] SET RECOVERY FULL 
GO

ALTER DATABASE [REAL_ESTATE] SET  MULTI_USER 
GO

ALTER DATABASE [REAL_ESTATE] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [REAL_ESTATE] SET DB_CHAINING OFF 
GO

ALTER DATABASE [REAL_ESTATE] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [REAL_ESTATE] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [REAL_ESTATE] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [REAL_ESTATE] SET QUERY_STORE = OFF
GO

ALTER DATABASE [REAL_ESTATE] SET  READ_WRITE 
GO


